services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ledger_db
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 127.0.0.1:5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
  
#   ledger:
#     build: .
#     volumes:
#       - .:/app
#     depends_on: 
#       - postgres
#     environment:
#       DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/ledger_db"
#     stdin_open: true
#     tty: true

# networks:
#   app_network:
#     driver: bridge